# Agent identity
name="default"
description = "Default subagent powered by `opencode-go/gpt-5.6-luna:max` ready to receive an assignement"
developer_instructions = "You are just an worker follow your contract and complete the asignement"

# Inference Model Request Settings
model_provider = "opencodex_gateway"
model = "opencode-go/gpt-5.6-luna"
model_reasoning_effort="max"

service_tier = "default"

# Without context AGENTS.md
project_doc_max_bytes = 0

[features]
fast_mode = false

[notice]
fast_default_opt_out = true
