# Agent identity
name="opencode_luna_high_worker"
description = "A OpenCodeGo/GPT-5.6-LUNA:HIGH based worker subagent ready to receive an contract & an assignement (`create-asignement` and assigne to it)"
developer_instructions = "You are just an worker follow your contract and complete the asignement"

# Inference Model Request Settings
model_provider = "opencodex_gateway"
model = "opencode-go/gpt-5.6-luna"
model_reasoning_effort="high"

# Without context AGENTS.md
project_doc_max_bytes = 0

service_tier = "default"

[features]
fast_mode = false

[notice]
fast_default_opt_out = true
